<?php
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MealSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $meals = [
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Grilled Chicken Salad',
                'description'             => 'A healthy salad with grilled chicken, lettuce, tomatoes, and olive oil.',
                'calories_per_serving'    => 350,
                'protein_grams'           => 30,
                'carbs_grams'             => 10,
                'fats_grams'              => 20,
                'fiber_grams'             => 5,
                'sugar_grams'             => 3,
                'sodium_mg'               => 400,
                'serving_size'            => 1,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => 'low-carb, high-protein',
                'ingredients'             => 'Chicken breast, Lettuce, Tomatoes, Olive oil, Salt, Pepper',
                'preparation_method'      => "Grill chicken\nChop vegetables\nMix with dressing",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 15,
                'total_time_minutes'      => 25,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Oatmeal with Fruits',
                'description'             => 'Warm oatmeal topped with fresh fruits and honey.',
                'calories_per_serving'    => 250,
                'protein_grams'           => 8,
                'carbs_grams'             => 45,
                'fats_grams'              => 5,
                'fiber_grams'             => 6,
                'sugar_grams'             => 15,
                'sodium_mg'               => 50,
                'serving_size'            => 1,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => 'vegetarian, high-fiber',
                'ingredients'             => 'Oats, Milk, Banana, Blueberries, Honey',
                'preparation_method'      => "Cook oats in milk\nTop with banana and blueberries\nDrizzle honey",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 10,
                'total_time_minutes'      => 15,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Turkey Sandwich',
                'description'             => 'Whole wheat sandwich with turkey, lettuce, and tomato.',
                'calories_per_serving'    => 320,
                'protein_grams'           => 25,
                'carbs_grams'             => 30,
                'fats_grams'              => 10,
                'fiber_grams'             => 5,
                'sugar_grams'             => 4,
                'sodium_mg'               => 600,
                'serving_size'            => 1,
                'serving_unit'            => 'sandwich',
                'dietary_tags'            => 'high-protein',
                'ingredients'             => 'Whole wheat bread, Turkey breast, Lettuce, Tomato, Mustard',
                'preparation_method'      => "Lay bread slices\nAdd turkey, lettuce, and tomato\nSpread mustard\nAssemble sandwich",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 0,
                'total_time_minutes'      => 5,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Spaghetti Bolognese',
                'description'             => 'Classic Italian pasta with ground beef and tomato sauce.',
                'calories_per_serving'    => 500,
                'protein_grams'           => 25,
                'carbs_grams'             => 60,
                'fats_grams'              => 18,
                'fiber_grams'             => 7,
                'sugar_grams'             => 8,
                'sodium_mg'               => 700,
                'serving_size'            => 1,
                'serving_unit'            => 'plate',
                'dietary_tags'            => 'high-carb',
                'ingredients'             => 'Spaghetti, Ground beef, Tomato sauce, Onion, Garlic, Olive oil',
                'preparation_method'      => "Cook spaghetti\nCook ground beef with onion and garlic\nAdd tomato sauce\nCombine pasta with sauce",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 30,
                'difficulty_level'        => 'Medium',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Greek Yogurt Parfait',
                'description'             => 'Layered Greek yogurt with granola and fresh berries.',
                'calories_per_serving'    => 220,
                'protein_grams'           => 12,
                'carbs_grams'             => 28,
                'fats_grams'              => 6,
                'fiber_grams'             => 4,
                'sugar_grams'             => 15,
                'sodium_mg'               => 70,
                'serving_size'            => 1,
                'serving_unit'            => 'cup',
                'dietary_tags'            => 'vegetarian, high-protein',
                'ingredients'             => 'Greek yogurt, Granola, Strawberries, Blueberries, Honey',
                'preparation_method'      => "Layer Greek yogurt\nAdd granola\nTop with berries\nDrizzle honey",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 0,
                'total_time_minutes'      => 5,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Quinoa Salad',
                'description'             => 'Protein-packed salad with quinoa, vegetables, and vinaigrette.',
                'calories_per_serving'    => 300,
                'protein_grams'           => 12,
                'carbs_grams'             => 35,
                'fats_grams'              => 12,
                'fiber_grams'             => 6,
                'sugar_grams'             => 5,
                'sodium_mg'               => 300,
                'serving_size'            => 1,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => 'vegan, high-fiber',
                'ingredients'             => 'Quinoa, Cucumber, Tomato, Bell pepper, Olive oil, Lemon juice',
                'preparation_method'      => "Cook quinoa\nChop vegetables\nMix quinoa with vegetables and dressing",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 15,
                'total_time_minutes'      => 25,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Avocado Toast',
                'description'             => 'Whole grain toast topped with mashed avocado and spices.',
                'calories_per_serving'    => 250,
                'protein_grams'           => 6,
                'carbs_grams'             => 28,
                'fats_grams'              => 14,
                'fiber_grams'             => 7,
                'sugar_grams'             => 2,
                'sodium_mg'               => 200,
                'serving_size'            => 1,
                'serving_unit'            => 'slice',
                'dietary_tags'            => 'vegetarian, low-sugar',
                'ingredients'             => 'Whole grain bread, Avocado, Salt, Pepper, Lemon juice',
                'preparation_method'      => "Toast bread\nMash avocado on top\nSeason with salt, pepper, and lemon juice",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 2,
                'total_time_minutes'      => 7,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Chicken Stir Fry',
                'description'             => 'Quick stir fry with chicken, broccoli, and bell peppers.',
                'calories_per_serving'    => 400,
                'protein_grams'           => 35,
                'carbs_grams'             => 25,
                'fats_grams'              => 15,
                'fiber_grams'             => 6,
                'sugar_grams'             => 6,
                'sodium_mg'               => 500,
                'serving_size'            => 1,
                'serving_unit'            => 'plate',
                'dietary_tags'            => 'high-protein, low-carb',
                'ingredients'             => 'Chicken breast, Broccoli, Bell peppers, Soy sauce, Garlic, Olive oil',
                'preparation_method'      => "Slice chicken\nChop vegetables\nStir fry chicken\nAdd vegetables\nAdd sauce and cook briefly",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 10,
                'total_time_minutes'      => 20,
                'difficulty_level'        => 'Medium',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Vegetable Soup',
                'description'             => 'Hearty soup with seasonal vegetables and herbs.',
                'calories_per_serving'    => 180,
                'protein_grams'           => 5,
                'carbs_grams'             => 20,
                'fats_grams'              => 8,
                'fiber_grams'             => 5,
                'sugar_grams'             => 4,
                'sodium_mg'               => 350,
                'serving_size'            => 1,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => 'vegan, low-calorie',
                'ingredients'             => 'Carrot, Celery, Onion, Potato, Tomato, Herbs, Olive oil',
                'preparation_method'      => "Chop vegetables\nSauté onion and garlic\nAdd vegetables and water\nSeason and simmer",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 30,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Salmon with Quinoa',
                'description'             => 'Baked salmon served with quinoa and steamed vegetables.',
                'calories_per_serving'    => 450,
                'protein_grams'           => 35,
                'carbs_grams'             => 35,
                'fats_grams'              => 18,
                'fiber_grams'             => 5,
                'sugar_grams'             => 3,
                'sodium_mg'               => 400,
                'serving_size'            => 1,
                'serving_unit'            => 'plate',
                'dietary_tags'            => 'high-protein, omega-3',
                'ingredients'             => 'Salmon fillet, Quinoa, Broccoli, Lemon, Olive oil',
                'preparation_method'      => "Preheat oven\nBake salmon with olive oil\nCook quinoa\nSteam vegetables\nServe together",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 30,
                'difficulty_level'        => 'Medium',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Fruit Smoothie',
                'description'             => 'Refreshing smoothie with mixed fruits and yogurt.',
                'calories_per_serving'    => 180,
                'protein_grams'           => 6,
                'carbs_grams'             => 35,
                'fats_grams'              => 2,
                'fiber_grams'             => 4,
                'sugar_grams'             => 25,
                'sodium_mg'               => 50,
                'serving_size'            => 1,
                'serving_unit'            => 'glass',
                'dietary_tags'            => 'vegetarian, low-fat',
                'ingredients'             => 'Banana, Berries, Yogurt, Honey, Ice',
                'preparation_method'      => "Add all ingredients to blender\nBlend until smooth\nServe chilled",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 0,
                'total_time_minutes'      => 5,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Egg Muffins',
                'description'             => 'Baked egg muffins with vegetables and cheese.',
                'calories_per_serving'    => 150,
                'protein_grams'           => 10,
                'carbs_grams'             => 5,
                'fats_grams'              => 10,
                'fiber_grams'             => 2,
                'sugar_grams'             => 2,
                'sodium_mg'               => 200,
                'serving_size'            => 2,
                'serving_unit'            => 'muffins',
                'dietary_tags'            => 'high-protein, low-carb',
                'ingredients'             => 'Eggs, Spinach, Bell peppers, Cheese, Salt, Pepper',
                'preparation_method'      => "Preheat oven\nBeat eggs and mix with vegetables and cheese\nPour into muffin tins\nBake 15-20 minutes",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 30,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Chickpea Salad',
                'description'             => 'Protein-rich salad with chickpeas, tomatoes, cucumber, and herbs.',
                'calories_per_serving'    => 280,
                'protein_grams'           => 12,
                'carbs_grams'             => 35,
                'fats_grams'              => 10,
                'fiber_grams'             => 8,
                'sugar_grams'             => 5,
                'sodium_mg'               => 300,
                'serving_size'            => 1,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => 'vegan, high-fiber',
                'ingredients'             => 'Chickpeas, Tomato, Cucumber, Olive oil, Lemon, Herbs',
                'preparation_method'      => "Rinse chickpeas\nChop vegetables\nMix with olive oil and lemon\nAdd herbs and season",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 0,
                'total_time_minutes'      => 10,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Peanut Butter Banana Toast',
                'description'             => 'Whole grain toast with peanut butter and sliced banana.',
                'calories_per_serving'    => 250,
                'protein_grams'           => 8,
                'carbs_grams'             => 30,
                'fats_grams'              => 12,
                'fiber_grams'             => 5,
                'sugar_grams'             => 10,
                'sodium_mg'               => 150,
                'serving_size'            => 1,
                'serving_unit'            => 'slice',
                'dietary_tags'            => 'vegetarian, high-energy',
                'ingredients'             => 'Whole grain bread, Peanut butter, Banana',
                'preparation_method'      => "Toast bread\nSpread peanut butter\nTop with banana slices",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 2,
                'total_time_minutes'      => 7,
                'difficulty_level'        => 'Easy',
                'is_active'               => true,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
        ];

        DB::table('meals')->insert($meals);
    }
}
