<?php
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MealSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $meals = [
            // ---------------- BREAKFAST ----------------
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Oatmeal with Banana & Almonds',
                'description'             => 'Creamy oats topped with banana slices and crunchy almonds.',
                'calories_per_serving'    => 400,
                'protein_grams'           => 12,
                'carbs_grams'             => 55,
                'fats_grams'              => 12,
                'fiber_grams'             => 8,
                'sugar_grams'             => 14,
                'sodium_mg'               => 120,
                'serving_size'            => 1.00,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => json_encode([
                    'category'   => 'breakfast',
                    'meal_times' => ['breakfast'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '1 cup oats',
                    '1 banana',
                    '2 tbsp almonds',
                    '1 cup milk',
                ]),
                'preparation_method'      => "Cook oats in milk.\nSlice banana.\nTop with almonds.",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 10,
                'total_time_minutes'      => 15,
                'difficulty_level'        => 'easy',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Yogurt with Apple & Walnuts',
                'description'             => 'Refreshing yogurt bowl with apple chunks and walnuts.',
                'calories_per_serving'    => 350,
                'protein_grams'           => 10,
                'carbs_grams'             => 40,
                'fats_grams'              => 15,
                'fiber_grams'             => 6,
                'sugar_grams'             => 18,
                'sodium_mg'               => 100,
                'serving_size'            => 1.00,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => json_encode([
                    'category'   => 'breakfast',
                    'meal_times' => ['breakfast'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '200g yogurt',
                    '1 apple',
                    '2 tbsp walnuts',
                ]),
                'preparation_method'      => "Cut apple into cubes.\nMix with yogurt.\nSprinkle walnuts.",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 0,
                'total_time_minutes'      => 5,
                'difficulty_level'        => 'easy',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Scrambled Eggs with Spinach',
                'description'             => 'Protein-rich scrambled eggs cooked with spinach.',
                'calories_per_serving'    => 280,
                'protein_grams'           => 20,
                'carbs_grams'             => 4,
                'fats_grams'              => 20,
                'fiber_grams'             => 3,
                'sugar_grams'             => 2,
                'sodium_mg'               => 320,
                'serving_size'            => 1.00,
                'serving_unit'            => 'plate',
                'dietary_tags'            => json_encode([
                    'category'   => 'breakfast',
                    'meal_times' => ['breakfast'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '2 eggs',
                    '100g spinach',
                    '1 tsp olive oil',
                ]),
                'preparation_method'      => "Whisk eggs.\nSauté spinach in olive oil.\nCook eggs together.",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 7,
                'total_time_minutes'      => 12,
                'difficulty_level'        => 'easy',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Banana Almond Smoothie',
                'description'             => 'A quick smoothie with banana, almonds, and milk.',
                'calories_per_serving'    => 300,
                'protein_grams'           => 9,
                'carbs_grams'             => 32,
                'fats_grams'              => 12,
                'fiber_grams'             => 4,
                'sugar_grams'             => 18,
                'sodium_mg'               => 100,
                'serving_size'            => 1.00,
                'serving_unit'            => 'glass',
                'dietary_tags'            => json_encode([
                    'category'   => 'breakfast',
                    'meal_times' => ['breakfast'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '1 banana',
                    '1 cup milk',
                    '2 tbsp almonds',
                ]),
                'preparation_method'      => "Blend banana, almonds, and milk until smooth.",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 0,
                'total_time_minutes'      => 5,
                'difficulty_level'        => 'easy',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Avocado Toast',
                'description'             => 'Toasted bread topped with mashed avocado.',
                'calories_per_serving'    => 270,
                'protein_grams'           => 8,
                'carbs_grams'             => 28,
                'fats_grams'              => 14,
                'fiber_grams'             => 7,
                'sugar_grams'             => 4,
                'sodium_mg'               => 240,
                'serving_size'            => 1.00,
                'serving_unit'            => 'plate',
                'dietary_tags'            => json_encode([
                    'category'   => 'breakfast',
                    'meal_times' => ['breakfast'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '2 slices bread',
                    '1/2 avocado',
                ]),
                'preparation_method'      => "Toast bread.\nMash avocado.\nSpread on toast.",
                'prep_time_minutes'       => 5,
                'cook_time_minutes'       => 2,
                'total_time_minutes'      => 7,
                'difficulty_level'        => 'easy',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ---------------- LUNCH ----------------
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Grilled Chicken with Quinoa & Spinach',
                'description'             => 'Grilled chicken served with quinoa and spinach.',
                'calories_per_serving'    => 520,
                'protein_grams'           => 45,
                'carbs_grams'             => 35,
                'fats_grams'              => 18,
                'fiber_grams'             => 6,
                'sugar_grams'             => 2,
                'sodium_mg'               => 430,
                'serving_size'            => 1.00,
                'serving_unit'            => 'plate',
                'dietary_tags'            => json_encode([
                    'category'   => 'lunch',
                    'meal_times' => ['lunch'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '200g chicken breast',
                    '150g quinoa',
                    '100g spinach',
                    '1 tbsp olive oil',
                ]),
                'preparation_method'      => "Grill chicken.\nCook quinoa.\nSauté spinach.\nServe together.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 30,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Salmon with Brown Rice & Broccoli',
                'description'             => 'Nutritious salmon fillet paired with rice and broccoli.',
                'calories_per_serving'    => 600,
                'protein_grams'           => 42,
                'carbs_grams'             => 45,
                'fats_grams'              => 20,
                'fiber_grams'             => 6,
                'sugar_grams'             => 2,
                'sodium_mg'               => 380,
                'serving_size'            => 1.00,
                'serving_unit'            => 'plate',
                'dietary_tags'            => json_encode([
                    'category'   => 'lunch',
                    'meal_times' => ['lunch'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '250g salmon',
                    '150g brown rice',
                    '100g broccoli',
                    '1 tbsp olive oil',
                ]),
                'preparation_method'      => "Bake salmon.\nCook rice.\nSteam broccoli.\nDrizzle olive oil.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 25,
                'total_time_minutes'      => 35,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Lentil & Chickpea Salad',
                'description'             => 'Plant-based salad with lentils, chickpeas, and olive oil.',
                'calories_per_serving'    => 420,
                'protein_grams'           => 24,
                'carbs_grams'             => 60,
                'fats_grams'              => 12,
                'fiber_grams'             => 14,
                'sugar_grams'             => 6,
                'sodium_mg'               => 250,
                'serving_size'            => 1.00,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => json_encode([
                    'category'   => 'lunch',
                    'meal_times' => ['lunch'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '150g lentils',
                    '150g chickpeas',
                    '50g spinach',
                    '1 tbsp olive oil',
                ]),
                'preparation_method'      => "Cook lentils and chickpeas.\nMix with spinach.\nAdd olive oil.",
                'prep_time_minutes'       => 15,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 35,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Tofu Stir-Fry with Rice',
                'description'             => 'Tofu cubes stir-fried with rice and vegetables.',
                'calories_per_serving'    => 450,
                'protein_grams'           => 20,
                'carbs_grams'             => 60,
                'fats_grams'              => 14,
                'fiber_grams'             => 6,
                'sugar_grams'             => 4,
                'sodium_mg'               => 350,
                'serving_size'            => 1.00,
                'serving_unit'            => 'plate',
                'dietary_tags'            => json_encode([
                    'category'   => 'lunch',
                    'meal_times' => ['lunch'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '150g tofu',
                    '150g white rice',
                    '100g broccoli',
                    '1 tbsp olive oil',
                ]),
                'preparation_method'      => "Cook rice.\nStir-fry tofu and broccoli in olive oil.\nCombine.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 30,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Chicken & Sweet Potato Bowl',
                'description'             => 'Balanced meal with chicken, sweet potato, and spinach.',
                'calories_per_serving'    => 510,
                'protein_grams'           => 40,
                'carbs_grams'             => 40,
                'fats_grams'              => 18,
                'fiber_grams'             => 7,
                'sugar_grams'             => 4,
                'sodium_mg'               => 420,
                'serving_size'            => 1.00,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => json_encode([
                    'category'   => 'lunch',
                    'meal_times' => ['lunch'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '200g chicken breast',
                    '200g sweet potato',
                    '50g spinach',
                    '1 tsp olive oil',
                ]),
                'preparation_method'      => "Grill chicken.\nRoast sweet potato.\nServe with spinach.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 25,
                'total_time_minutes'      => 35,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ---------------- DINNER ----------------
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Salmon with Quinoa & Spinach',
                'description'             => 'Evening meal with salmon, quinoa, and greens.',
                'calories_per_serving'    => 580,
                'protein_grams'           => 42,
                'carbs_grams'             => 35,
                'fats_grams'              => 22,
                'fiber_grams'             => 6,
                'sugar_grams'             => 2,
                'sodium_mg'               => 370,
                'serving_size'            => 1.00,
                'serving_unit'            => 'plate',
                'dietary_tags'            => json_encode([
                    'category'   => 'dinner',
                    'meal_times' => ['dinner'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '200g salmon',
                    '150g quinoa',
                    '100g spinach',
                    '1 tbsp olive oil',
                ]),
                'preparation_method'      => "Bake salmon.\nCook quinoa.\nSauté spinach.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 25,
                'total_time_minutes'      => 35,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Chicken & Broccoli Rice Bowl',
                'description'             => 'Classic chicken rice bowl with steamed broccoli.',
                'calories_per_serving'    => 520,
                'protein_grams'           => 42,
                'carbs_grams'             => 48,
                'fats_grams'              => 14,
                'fiber_grams'             => 5,
                'sugar_grams'             => 2,
                'sodium_mg'               => 410,
                'serving_size'            => 1.00,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => json_encode([
                    'category'   => 'dinner',
                    'meal_times' => ['dinner'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '200g chicken breast',
                    '150g white rice',
                    '100g broccoli',
                    '1 tsp olive oil',
                ]),
                'preparation_method'      => "Grill chicken.\nCook rice.\nSteam broccoli.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 30,
                'difficulty_level'        => 'easy',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Tofu & Lentil Curry Bowl',
                'description'             => 'Hearty tofu and lentil curry served with spinach.',
                'calories_per_serving'    => 480,
                'protein_grams'           => 28,
                'carbs_grams'             => 50,
                'fats_grams'              => 14,
                'fiber_grams'             => 10,
                'sugar_grams'             => 3,
                'sodium_mg'               => 380,
                'serving_size'            => 1.00,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => json_encode([
                    'category'   => 'dinner',
                    'meal_times' => ['dinner'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '150g tofu',
                    '150g lentils',
                    '100g spinach',
                    '1 tbsp olive oil',
                ]),
                'preparation_method'      => "Cook lentils.\nSauté tofu and spinach.\nMix with lentils and olive oil.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 20,
                'total_time_minutes'      => 30,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Chicken & Sweet Potato Bowl',
                'description'             => 'Balanced dinner with chicken, roasted sweet potato, and spinach.',
                'calories_per_serving'    => 510,
                'protein_grams'           => 40,
                'carbs_grams'             => 40,
                'fats_grams'              => 18,
                'fiber_grams'             => 7,
                'sugar_grams'             => 4,
                'sodium_mg'               => 420,
                'serving_size'            => 1.00,
                'serving_unit'            => 'bowl',
                'dietary_tags'            => json_encode([
                    'category'   => 'dinner',
                    'meal_times' => ['dinner'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '200g chicken breast',
                    '200g sweet potato',
                    '50g spinach',
                    '1 tsp olive oil',
                ]),
                'preparation_method'      => "Grill chicken.\nRoast sweet potato.\nServe with spinach.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 25,
                'total_time_minutes'      => 35,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
            [
                'created_by_dietitian_id' => 2,
                'meal_name'               => 'Salmon with Sweet Potato & Broccoli',
                'description'             => 'Oven-baked salmon served with roasted sweet potato and steamed broccoli.',
                'calories_per_serving'    => 600,
                'protein_grams'           => 45,
                'carbs_grams'             => 40,
                'fats_grams'              => 22,
                'fiber_grams'             => 7,
                'sugar_grams'             => 5,
                'sodium_mg'               => 380,
                'serving_size'            => 1.00,
                'serving_unit'            => 'plate',
                'dietary_tags'            => json_encode([
                    'category'   => 'dinner',
                    'meal_times' => ['dinner'],
                    'is_public'  => true,
                ]),
                'ingredients'             => json_encode([
                    '200g salmon',
                    '150g sweet potato',
                    '100g broccoli',
                    '1 tbsp olive oil',
                ]),
                'preparation_method'      => "Bake salmon.\nRoast sweet potato.\nSteam broccoli.\nDrizzle with olive oil.",
                'prep_time_minutes'       => 10,
                'cook_time_minutes'       => 25,
                'total_time_minutes'      => 35,
                'difficulty_level'        => 'medium',
                'is_active'               => 1,
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
        ];

        DB::table('meals')->insert($meals);
    }
}
